[workspace]
name = "py-ctcmetrics"
description = "Metrics for Cell Tracking Challenges"
authors = ["Timo Kaiser <kaiser@tnt.uni-hannover.de>"]
repository = "https://github.com/CellTrackingChallenge/py-ctcmetrics.git"
version = "1.3.1"

readme = "../README.md"
license = "BSD-2-Clause"
license-file = "../LICENSE.txt"

platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
channels = ["conda-forge"]

[dependencies]
numpy = ">=2.3.2,<3"
scikit-learn = ">=1.7.1,<2"
tifffile = ">=2025.8.28,<2026"
imagecodecs = ">=2025.8.2,<2026"
pandas = ">=2.3.2,<3"
scipy = ">=1.16.1,<2"
py-opencv = ">=4.12.0,<5"

[pypi-dependencies]
py-ctcmetrics = { path = "..", editable = true }
